---
# vim: set ft=ansible ts=2 sw=2 et:

- name: rsyslog 
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^$FileCreateMode '
    line: '$FileCreateMode 0640'
    insertafter: '#### GLOBAL DIRECTIVES ####'
  notify: restart_rsyslog

# TODO:
#module(load="imklog") # reads kernel messages (the same are read from journald)
#module(load"immark") # provides --MARK-- message capability

