---
# vim: set ft=ansible

- name: Ensure sysctl fs.suid_dumpable is set to 0
  sysctl:
    name: fs.suid_dumpable
    value: "0"
    state: present
    reload: yes

- name: Ensure sysctl net.ipv4.conf.all.accept_redirects is set to 0
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "0"
    state: present
    reload: yes

- name: Ensure sysctl net.ipv4.ip_forward is set to 0
  sysctl:
    name: net.ipv4.ip_forward
    value: "0"
    state: present
    reload: yes

- name: Ensure sysctl net.ipv4.conf.all.secure_redirects is set to 0
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: "0"
    state: present
    reload: yes

- name: Ensure sysctl net.ipv4.conf.default.secure_redirects is set to 0
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: "0"
    state: present
    reload: yes

#NOTE: this one is noisey and i persinally don't like it.
- name: Ensure sysctl net.ipv4.conf.all.log_martians is set to 1
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: "1"
    state: present
    reload: yes

#NOTE: this one is noisey and i persinally don't like it.
- name: Ensure sysctl net.ipv4.conf.default.log_martians is set to 1
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: "1"
    state: present
    reload: yes
