---
# vim: set ft=ansible

########################################################
#- block:
#  - name: Red Hat based upgrade
#    yum:
#      name: '*'
#      state: latest
#
#  - name: yum history
#    command: yum history info
#    args:
#      warn: false # set warn=false to prevent warning
#    register: packages
#
#  - name: Upgraded packages
#    debug: var=packages.stdout_lines
#
#  when: ansible_os_family == "RedHat"

########################################################
- block:
  - name: Debian based upgrade
    apt: 
      upgrade: yes 
      update_cache: yes
    register: packages
  
  - name: Upgraded packages
    debug: var=packages

  when: ansible_os_family == "Debian"




