---
- name: Install the repository into DNF for docker
  command: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int == 8

- name: Install the repository into yum for docker
  become: true
  command: "yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int == 7

- name: Install the required base packages into apt for docker
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
  when:
    - ansible_os_family == 'Debian'

- name: Add apt signing key for docker
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when:
    - ansible_os_family == 'Debian'

# TODO: Make bionic a variable - probably wait until focal support exists
- name: Install the repository into apt for docker
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: Install a version of docker that Rancher supports
  become: true
  package:
    name:
      - docker-ce=5:19.03.15~3-0~ubuntu-bionic
      - docker-ce-cli=5:19.03.15~3-0~ubuntu-bionic
      - containerd.io=1.4.3-1
    state: present
    force: True

- name: Install deps for python
  become: true
  package:
    name:
      - epel-release
    state: latest
  when:
    - ansible_os_family == 'RedHat'

- name: Install docker compose dependencies
  become: true
  package:
    name:
      - openssl
      - python-devel
      - python-pip
    state: latest
  when:
    - ansible_os_family == 'RedHat'

- name: Remove stuff
  become: true
  package:
    name:
      - python-requests
    state: absent
  when:
    - ansible_os_family == 'RedHat'

- name: Install pip on RedHat
  become: true
  pip:
    name: pip
    state: latest
  when:
    - ansible_os_family == 'RedHat'

- name: Update pip version to prevent docker-compose install failure
  command: python3 -m pip install -U pip

- name: Install docker-compose and docker python bindings on
  become: true
  pip:
    name:
      - docker-compose
    executable: pip3

- name: Template docker daemon file
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: docker_insecure_registries | length>0
  notify:
    - restart docker

- name: Ensure ipv4 forwarding is enabled
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Make sure docker is running & enabled
  become: true
  systemd:
    state: started
    enabled: yes
    name: docker
