# Install ansible dependencies for VMware environment
- name: upgrade pip
  become: true
  pip:
    name: pip
    state: latest

- name: Install dependencies
  pip:
    name:
      - pyvmomi
      - boto3
      - botocore
      - requests
      - jsonschema
      - setuptools
    state: latest
    executable: pip3

- name: Install Python vSphere automation SDK
  command: "python3 -m pip install --user --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git"

