---
# vim: set ft=ansible

chrony_max_poll: 10
var_accounts_passwords_pam_faillock_deny: 3
var_accounts_passwords_pam_faillock_unlock_time: never
var_accounts_passwords_pam_faillock_fail_interval: 900
var_password_pam_unix_remember: 5
var_password_pam_minlen: 15
var_password_pam_maxclassrepeat: 4
var_password_pam_maxrepeat: 3
var_password_pam_dcredit: -1
var_password_pam_minclass: 4
var_password_pam_difok: 8
var_password_pam_ocredit: -1
var_password_pam_lcredit: -1
var_password_pam_ucredit: -1
var_accounts_max_concurrent_login_sessions: 10
etc_issue_contents: |
  *****************************************************************************
  *                                  WARNING                                  *
  *****************************************************************************


  *****************************************************************************
  *             DO NOT PROCEED IF YOU ARE NOT AN AUTHORISED USER              *
  *****************************************************************************

var_accounts_minimum_age_login_defs: 7
var_accounts_warning_age_login_defs: 7
var_accounts_maximum_age_login_defs: 60
var_account_disable_post_pw_expiration: 0

# OLD sshd_approved_macs: "hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com"
sshd_approved_macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
# these are not valid : curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# OLD sshd_approved_ciphers: "aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc"
sshd_approved_ciphers: "aes256-ctr,aes192-ctr,aes128-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com"
