- name: Install App Gateway Applications
  hosts: localhost
  become: true
  vars:
    ansible_ssh_user: "ubuntu"
    ansible_interpreter: "/usr/bin/python3"
  roles:
    - name: app_gateway
    - name: ssh_ad_packages
    - name: nfs
    - name: journald
    - name: logrhythm
