---
- name: Install nfs server
  hosts: all
  become: yes
  vars:
    ansible_ssh_user: "ubuntu"
    ansible_interpreter: "/usr/bin/python3"
  roles:
    - ssh_ad_packages
    - nfs_server
    - logrhythm
