---
- name: Install postgres and dependencies
  hosts: all
  become: yes
  vars:
    ansible_ssh_user: "ubuntu"
    ansible_interpreter: "/usr/bin/python3"
  roles:
    - postgres
    - ssh_ad_packages
    - keepalived
    - nfs
    - journald
    - logrhythm
